# Generated by Django 4.2.3 on 2023-07-28 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop_group',
            name='season_id',
            field=models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.seasons'),
        ),
        migrations.AlterField(
            model_name='crop_group',
            name='year_id',
            field=models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.years'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='crop_group_id',
            field=models.ForeignKey(db_column='crop_group_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.crop_group'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='indicator_id',
            field=models.ForeignKey(db_column='indicator_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.indicators'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='season_id',
            field=models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.seasons'),
        ),
        migrations.AlterField(
            model_name='crops',
            name='unit_id',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.unit'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='age_range_id',
            field=models.ForeignKey(db_column='age_range_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.age_range'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='crop_group_id',
            field=models.ForeignKey(db_column='crop_group_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.crop_group'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='district_id',
            field=models.ForeignKey(db_column='district_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.district'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='gender_id',
            field=models.ForeignKey(db_column='gender_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.gender'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='province_id',
            field=models.ForeignKey(db_column='province_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.province'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='sectors_of_employment_id',
            field=models.ForeignKey(db_column='sectors_of_employment_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.sectors_of_employment'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='source_id',
            field=models.ForeignKey(db_column='source_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.source'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='theme_id',
            field=models.ForeignKey(db_column='theme_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.themes'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='unit_id',
            field=models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.unit'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='urbanization_id',
            field=models.ForeignKey(db_column='urbanization_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.urbanization'),
        ),
        migrations.AlterField(
            model_name='indicators',
            name='year_id',
            field=models.ForeignKey(db_column='year_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.years'),
        ),
    ]
