# Generated by Django 4.2.3 on 2023-08-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='indicators_groups',
            table='indicators_groups',
        ),
    ]
