# Generated by Django 4.2.3 on 2023-08-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_alter_indicators_groups_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sectors_of_employment',
            table='sectors_of_employment',
        ),
    ]
