# Generated by Django 4.2.3 on 2023-07-31 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_remove_indicators_crop_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicators',
            name='sectors_of_employment_id',
            field=models.ForeignKey(db_column='sectors_of_employment_id', on_delete=django.db.models.deletion.CASCADE, to='indicators.sectors_of_employment'),
        ),
    ]
