# Generated by Django 4.2.3 on 2023-08-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_alter_sectors_of_employment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='themes_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'themestest',
            },
        ),
    ]
