# Generated by Django 4.2.3 on 2023-07-28 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0004_age_range_crop_group_district_enterprise_size_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crop_group',
            table='crop_group',
        ),
        migrations.AlterModelTable(
            name='crops',
            table='crops',
        ),
        migrations.AlterModelTable(
            name='indicators',
            table='indicators',
        ),
    ]
