# Generated by Django 4.2.3 on 2023-07-31 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_rename_sectors_of_employment_sector_of_employment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='indicator_id',
            field=models.ForeignKey(db_column='indicator_id', on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='indicators.indicators'),
        ),
    ]
